'use client'

import { useState, useEffect } from 'react'
import Link from 'next/link'
import { Play, Check, Timer } from 'lucide-react'
import { useRouter } from 'next/navigation'
import { useMember } from '@/context/MemberContext'

type UnifiedTask = {
    id: string
    title: string
    points: number
    durationMinutes: number | null
    isRoutine: boolean
    // Routine / Task specific
    type?: 'EARN' | 'HOURGLASS' | 'SPEND' | 'TATTLE'
    isCompletedDaily?: boolean
    timeOfDay?: string
    activeTaskId?: string | null
    // Task specific
    scheduledAt?: string | null
}

export default function TodoTasksList({ memberId, hideStartButton = false }: { memberId: string, hideStartButton?: boolean }) {
    const router = useRouter()
    const { currentMember } = useMember()
    const [items, setItems] = useState<UnifiedTask[]>([])
    const [loading, setLoading] = useState(true)

    const fetchItems = async () => {
        if (!currentMember?.familyId) return
        try {
            const [tasksRes, routinesRes] = await Promise.all([
                fetch(`/api/tasks?status=TODO&familyId=${currentMember.familyId}`),
                fetch(`/api/routines/today?memberId=${memberId}`)
            ])

            const tasksData = await tasksRes.json()
            const routinesData = await routinesRes.json()

            let unifiedList: UnifiedTask[] = []

            if (Array.isArray(tasksData)) {
                // Filter out tasks that are generated by a routine (they are rendered as routines)
                const myTodoTasks = tasksData.filter(t => (t.assigneeId || t.creatorId) === memberId && t.status === 'TODO' && !t.routineId)
                unifiedList = [...unifiedList, ...myTodoTasks.map(t => ({
                    ...t,
                    isRoutine: false
                }))]
            }

            if (Array.isArray(routinesData)) {
                unifiedList = [...unifiedList, ...routinesData.map((r: any) => ({
                    ...r,
                    isRoutine: true
                }))]
            }

            // Filter out completed routines as requested
            unifiedList = unifiedList.filter(item => !item.isCompletedDaily)

            setItems(unifiedList)
        } catch (e) {
            console.error(e)
        } finally {
            setLoading(false)
        }
    }

    useEffect(() => {
        fetchItems()
    }, [memberId])

    const handleRoutineClick = async (routine: UnifiedTask) => {
        if (routine.isCompletedDaily || !currentMember) return

        if (routine.activeTaskId) {
            if (routine.type === 'EARN') {
                // If it's EARN, bypass the timer execution page and just complete it
                const res = await fetch(`/api/tasks/${routine.activeTaskId}`, {
                    method: 'PATCH',
                    headers: { 'Content-Type': 'application/json' },
                    body: JSON.stringify({ status: 'PENDING' })
                })
                if (res.ok) fetchItems()
            } else {
                router.push(`/tasks/${routine.activeTaskId}/execute`)
            }
            return
        }

        if (routine.type === 'EARN') {
            const res = await fetch('/api/tasks', {
                method: 'POST', body: JSON.stringify({
                    title: routine.title,
                    description: '루틴 달성으로 인한 콩 적립! 🌱',
                    type: 'EARN',
                    points: routine.points,
                    creatorId: currentMember.id,
                    routineId: routine.id
                })
            })
            // Immediately dispatch it as pending so it skips the TODO phase entirely.
            // This is safer since /api/tasks sets new EARN to TODO.
            if (res.ok) {
                const createdTask = await res.json()
                if (createdTask.id) {
                    await fetch(`/api/tasks/${createdTask.id}`, {
                        method: 'PATCH',
                        headers: { 'Content-Type': 'application/json' },
                        body: JSON.stringify({ status: 'PENDING' })
                    })
                }
                fetchItems()
            }
        } else if (routine.type === 'HOURGLASS') {
            const res = await fetch('/api/tasks', {
                method: 'POST', body: JSON.stringify({
                    title: routine.title,
                    description: '루틴 타이머 수행 중...',
                    type: 'HOURGLASS',
                    points: routine.points,
                    creatorId: currentMember.id,
                    targetMemberId: currentMember.id,
                    durationMinutes: routine.durationMinutes,
                    routineId: routine.id
                })
            })
            const task = await res.json()
            if (task.id) {
                router.push(`/tasks/${task.id}/execute`)
            }
        }
    }

    const handleTaskClick = async (task: UnifiedTask) => {
        if (!currentMember) return

        if (task.type === 'EARN') {
            // Directly complete the task and send to PENDING queue
            const res = await fetch(`/api/tasks/${task.id}`, {
                method: 'PATCH',
                headers: { 'Content-Type': 'application/json' },
                body: JSON.stringify({ status: 'PENDING' })
            })
            if (res.ok) fetchItems()
        } else if (task.type === 'SPEND' || task.type === 'TATTLE') {
            // For SPEND or TATTLE, immediately complete and AUTO-APPROVE
            const res = await fetch(`/api/tasks/${task.id}`, {
                method: 'PATCH',
                headers: { 'Content-Type': 'application/json' },
                body: JSON.stringify({ status: 'PENDING' })
            })
            if (res.ok) {
                // Instantly call the auto-approve API to deductive points
                await fetch(`/api/tasks/${task.id}/approve`, {
                    method: 'POST',
                    headers: { 'Content-Type': 'application/json' },
                    body: JSON.stringify({ action: 'APPROVE' })
                })
                fetchItems()
            }
        } else {
            // HOURGLASS goes to execute page
            router.push(`/tasks/${task.id}/execute`)
        }
    }

    if (loading) return <div style={{ textAlign: 'center', color: '#90A4AE', fontSize: '0.9rem' }}>로딩 중...</div>

    if (items.length === 0) {
        return (
            <div style={{ background: 'rgba(255,255,255,0.4)', borderRadius: '16px', padding: '1.5rem', textAlign: 'center', color: '#607D8B' }}>
                <span style={{ fontSize: '1.5rem', display: 'block', marginBottom: '8px' }}>🎉</span>
                지금 당장 해야 할 일이나 루틴은 없어요!<br />휴식을 취하거나 새로운 일을 찾아볼까요?
            </div>
        )
    }

    return (
        <div style={{ display: 'flex', flexDirection: 'column', gap: '0.8rem' }}>
            {items.map(item => (
                <div key={`${item.isRoutine ? 'r' : 't'}-${item.id}`} className="card" style={{
                    display: 'flex', alignItems: 'center', justifyContent: 'space-between',
                    background: item.isCompletedDaily ? '#ECEFF1' : 'white',
                    opacity: item.isCompletedDaily ? 0.7 : 1,
                    padding: '12px 16px', borderRadius: '16px',
                    boxShadow: '0 2px 8px rgba(0,0,0,0.05)',
                    border: '1px solid transparent',
                    transition: 'transform 0.2s cubic-bezier(0.4, 0, 0.2, 1)',
                    marginBottom: 0
                }}>
                    <div>
                        <div style={{ fontWeight: 'bold', color: '#37474F', fontSize: '1.05rem', marginBottom: '4px', display: 'flex', alignItems: 'center', gap: '6px' }}>
                            {item.title}
                            {item.isRoutine && (
                                <span style={{ fontSize: '0.7rem', padding: '2px 6px', background: 'rgba(255, 213, 79, 0.2)', color: '#F57F17', borderRadius: '8px', fontWeight: 'bold' }}>
                                    루틴 🔁
                                </span>
                            )}
                        </div>
                        <div style={{ fontSize: '0.85rem', color: '#78909C', display: 'flex', gap: '8px', alignItems: 'center' }}>
                            {item.isRoutine && item.timeOfDay && <span>⏰ {item.timeOfDay}</span>}
                            {item.durationMinutes && <span>⏱️ {item.durationMinutes}분</span>}
                            <span style={{ color: (item.type === 'SPEND' || item.type === 'TATTLE') ? '#FF5252' : '#FBC02D', fontWeight: 'bold' }}>
                                {(item.type === 'SPEND' || item.type === 'TATTLE') ? '-' : '+'}{Math.abs(item.points)}콩
                            </span>
                        </div>
                    </div>
                    {!hideStartButton && (
                        item.isRoutine ? (
                            <button
                                disabled={item.isCompletedDaily}
                                onClick={() => handleRoutineClick(item)}
                                className={item.isCompletedDaily ? "btn" : "btn btn-primary"}
                                style={{
                                    padding: '8px 16px', fontSize: '0.85rem', borderRadius: '12px',
                                    border: 'none', display: 'flex', gap: '4px', alignItems: 'center',
                                    ...(item.isCompletedDaily ? { background: '#B0BEC5', color: 'white', boxShadow: 'none' } : {})
                                }}
                            >
                                {item.isCompletedDaily ? '완료 🎉' : (item.type === 'HOURGLASS' ? <><Timer size={16} /> 시작</> : <><Check size={16} /> 완료</>)}
                            </button>
                        ) : (
                            <button
                                onClick={() => handleTaskClick(item)}
                                className="btn btn-primary"
                                style={{
                                    padding: '8px 16px', fontSize: '0.85rem', borderRadius: '12px',
                                    border: 'none', display: 'flex', gap: '4px', alignItems: 'center',
                                    fontFamily: 'inherit'
                                }}
                            >
                                {item.type === 'HOURGLASS' ? <><Timer size={16} /> 시작</> : <><Check size={16} /> 완료</>}
                            </button>
                        )
                    )}
                </div>
            ))}
        </div>
    )
}
